services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DEEPVITAL_POSTGRES_USER:-deepvital_user}
      POSTGRES_PASSWORD: ${DEEPVITAL_POSTGRES_PASSWORD:-change-me}
      POSTGRES_DB: ${DEEPVITAL_POSTGRES_DB:-deepvital}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DEEPVITAL_PGADMIN_EMAIL:-admin@example.invalid}
      PGADMIN_DEFAULT_PASSWORD: ${DEEPVITAL_PGADMIN_PASSWORD:-change-me}
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - db

volumes:
  pgdata:
